version: "3"

services:
  api:
    build: "./api"
    ports:
      - "5000:5000"
  pipelines:
    build: "./mlops"
    ports:
      - "8443:8443"
  app:
    build: "./app"
    ports:
      - "8080:8080"
