// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6bm3Kepo5r3116JWd0vBxSN54MFqLyQY',
    appId: '1:290150145717:web:92f2833c7b253494f7e8fc',
    messagingSenderId: '290150145717',
    projectId: 'b4b-comfort-20eeb',
    authDomain: 'b4b-comfort-20eeb.firebaseapp.com',
    storageBucket: 'b4b-comfort-20eeb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEugfedDxSAyttZvA_LmkIwiyLW28KEGQ',
    appId: '1:290150145717:android:9cda28cb49e22d7ff7e8fc',
    messagingSenderId: '290150145717',
    projectId: 'b4b-comfort-20eeb',
    storageBucket: 'b4b-comfort-20eeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR8_UyVRDNUdzUNz9f2p5rb3icq2qCrpk',
    appId: '1:290150145717:ios:9b4f59333d67102bf7e8fc',
    messagingSenderId: '290150145717',
    projectId: 'b4b-comfort-20eeb',
    storageBucket: 'b4b-comfort-20eeb.appspot.com',
    iosClientId: '290150145717-pklvs5jldjsbo1etkumsqbh22bniqqfb.apps.googleusercontent.com',
    iosBundleId: 'com.nitantupasani.b4bhhsselfreporting',
  );
}
